version: '3'

volumes:
  db_data: {}
  wordpress_data: {}

services:
  # MariaDB Database Service
  db:
    image: mariadb:10.6
    container_name: woocommerce_db # Hardcoded name
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
    restart: unless-stopped
    

  # WordPress / WooCommerce Backend (Custom Image with Plugin Pre-installed)
  wordpress:
    build:
      context: ./wordpress-custom
    container_name: woocommerce_app # Hardcoded name
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_SITEURL: ${WORDPRESS_SITE_URL}
      WORDPRESS_HOME: ${WORDPRESS_HOME_URL}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - web
      - internal
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-backend.rule=(Host(`${WORDPRESS_SITE_URL_HOST}`) || Host(`www.${WORDPRESS_SITE_URL_HOST}`)) && (PathPrefix(`/wp-admin`) || PathPrefix(`/wp-login.php`) || PathPrefix(`/wp-json`) || PathPrefix(`/wp-content`) || PathPrefix(`/wp-includes`))"
      - "traefik.http.routers.wordpress-backend.entrypoints=websecure"
      - "traefik.http.routers.wordpress-backend.tls.certresolver=cloudflare"
      - "traefik.http.routers.wordpress-backend.priority=20"
      - "traefik.http.services.wordpress-service.loadbalancer.server.port=9000"
      - "traefik.docker.network=web"

  # React App (The WooCommerce Frontend)
  webshop-react-app:
    build:
      context: ./webshop-react-app
      args:
        - REACT_APP_CLERK_PUBLISHABLE_KEY=${REACT_APP_CLERK_PUBLISHABLE_KEY}
        - REACT_APP_WORDPRESS_API_URL=${WORDPRESS_SITE_URL}/wp-json
    container_name: hangtal # Hardcoded name
    restart: always
    depends_on:
      wordpress:
        condition: service_started
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webshop-frontend.rule=Host(`${WORDPRESS_SITE_URL_HOST}`) || Host(`www.${WORDPRESS_SITE_URL_HOST}`)"
      - "traefik.http.routers.webshop-frontend.entrypoints=websecure"
      - "traefik.http.routers.webshop-frontend.tls=true"
      - "traefik.http.routers.webshop-frontend.tls.certresolver=cloudflare"
      - "traefik.http.services.webshop-frontend-service.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
  internal:
    internal: true