version: "3"

services:
  stripe-backend:
    build:
      context: .
    container_name: stripe-backend
    restart: unless-stopped
    ports:
      - "4242:4242"  # Optional: remove this in production
    env_file:
      - .env
    labels:
      - "traefik.enable=true"

      # Stripe checkout route
      - "traefik.http.routers.stripe-checkout.rule=Host(`zvukovaakademia.sk`) && Path(`/create-checkout-session`)"
      - "traefik.http.routers.stripe-checkout.entrypoints=websecure"
      - "traefik.http.routers.stripe-checkout.methods=POST"
      - "traefik.http.routers.stripe-checkout.service=stripe-backend-service"
      - "traefik.http.routers.stripe-checkout.tls=true"
      - "traefik.http.routers.stripe-checkout.tls.certresolver=cloudflare"

      # Stripe API general route
      - "traefik.http.routers.stripe-api-general.rule=Host(`zvukovaakademia.sk`) && PathPrefix(`/api`)"
      - "traefik.http.routers.stripe-api-general.entrypoints=websecure"
      - "traefik.http.routers.stripe-api-general.service=stripe-backend-service"
      - "traefik.http.routers.stripe-api-general.methods=GET,POST,PUT,DELETE"
      - "traefik.http.routers.stripe-api-general.tls=true"
      - "traefik.http.routers.stripe-api-general.tls.certresolver=cloudflare"

      # Define service port
      - "traefik.http.services.stripe-backend-service.loadbalancer.server.port=4242"
      - "traefik.http.services.stripe-backend-service.loadbalancer.server.scheme=http"

    networks:
      - web

networks:
  web:
    external: true
