version: "3"

services:
  stripe-backend:
    build:
      context: .
    container_name: stripe-backend
    restart: unless-stopped
    ports:
      - "4242:4242"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - >-
        traefik.http.routers.stripe.rule=Host(`api.lifeisnatural.eu`) && (
          PathPrefix(`/create-checkout-session`) || 
          PathPrefix(`/api`) || 
          PathPrefix(`/success.html`) || 
          PathPrefix(`/cancel.html`)
        )
      - "traefik.http.routers.stripe.entrypoints=websecure"
      - "traefik.http.services.stripe.loadbalancer.server.port=4242"
    networks:
      - web

networks:
  web:
    external: true
